### ISSUE TITLE
Solve minimist security issue

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/bambi-scoreboard#10]
dependabot says `Upgrade minimist to version 1.2.3 or later` but cannot do it automagically because conflicts

**Comment by ldruschk** [comment]
Yeah I am aware of that, when I last checked it Dependabot was trying to create the PR but silently failed later

**Comment by ldruschk** [comment]
I honestly have no idea what problem Dependabot had with this, a simple `npm install minimist` seemed to fix it

**Comment by ldruschk** [comment]
Apparently the yarn lock is different from the package lock, but it actually should be fixed now :D
