### ISSUE TITLE
Services on the team page are not ordered correctly

### ISSUE THREAD

**Issue by ldruschk** [enowars/bambi-scoreboard#9]
They are displayed in the order returned by the engine and not ordered by index

**Comment by Trolldemorted** [comment]
Should the engine enforce the order?

**Comment by ldruschk** [comment]
Might be helpful for the dozens of alternative scoreboards (that will be implemented eventually given how ENOFLAG usually works), but for the current scoreboard it doesn't matter

**Comment by Trolldemorted** [comment]
in https://github.com/enowars/EnoEngine/commit/58d24790095a0faf4b74dc99f7f47e610dbf86e5
